In [116]:
start = time.time()

#URL = 'https://drive.google.com/file/d/1Q997Mig3nQZXkWl2IPrjibi_nDtJ-tz4/view?usp=share_link'
#path = 'https://drive.google.com/uc?export=download&id='+URL.split('/')[-2]

data_csv = pd.read_csv(path, encoding = "Windows-1252", sep = ';', low_memory=False)

elapsed_time = time.time() - start

operator_column = data_csv['oper']

operator_column.value_counts()

print('Enlapsed time: ', elapsed_time)

data_csv.head()

Enlapsed time:  27.83926272392273

,data,ora,st,oper,operazione,nota,prodotto,codice,ditta prod.,imp/sc,pezzi,giac,var. bd,var. mag.
0,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,PRANAROM CIRCULAR BIOGELGAMB,979817778.0,HERBALGEM ITALIA S,"16,35 €",NaN,NaN,"-0,15",NaN
1,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,PRANAROM AROMAPIC GELLEN40ML,979817754.0,HERBALGEM ITALIA S,"10,95 €",NaN,NaN,"10,95",NaN
2,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,OLIO SMAGLIATURE 100ML,978868053.0,WELEDA ITALIA SRL,"21,40 €",NaN,1,"0,4","0,4"
3,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,BABY CREMA PROTETTIVACAL75ML,978867974.0,WELEDA ITALIA SRL,"10,70 €",NaN,2,"0,2","0,4"
4,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,DECOTTO DI BETULLA 250ML,976785865.0,WELEDA ITALIA SRL,"17,30 €",NaN,NaN,"0,3",NaN

In [107]:

a = set()
b = set()
ab = set()

file = csv.reader(open(path), delimiter=find_delimiter('./Fact_Tables/pharma.csv'))

for row in file:
    if (row[8] != "") and (row[6] != ""):
        a.add(row[8])
        b.add(row[6])
        ab.add(row[8] + " - " + row[6])

print("a:", len(a))
print("b:", len(b))
print("ab:", len(ab))
print(len(ab)-len(b))

IndexError: list index out of range

In [47]:
# Read the extension from the importing url

import os


filename, file_extension = os.path.splitext(url)

filename
#'/path/to/somefile'
file_extension
#'.ext'

TypeError: expected str, bytes or os.PathLike object, not HTTPResponse

In [9]:
import csv

# Funzione che identifica il delimitatore del file csv
# Output: stringa contenente il delimitatore
def find_delimiter(filename):
    sniffer = csv.Sniffer()
    with open(filename) as fp:
        delimiter = sniffer.sniff(fp.read(5000)).delimiter
    return delimiter

';'

In [93]:
import chardet

def find_delimiter(filename):
    with open(filename, 'rb') as rawdata:
        result = chardet.detect(rawdata.read(10000))

    # check what the character encoding might be
    print(result)
    
pippo = find_delimiter("./Fact_Tables/pharma.csv")
print(type(pippo))

{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}
<class 'NoneType'>

In [21]:
# consideriamo i file exel

import time

import pandas as pd

start = time.time()

data_exel = pd.read_excel('./Fact_Tables/pharma.xlsx')

elapsed_time = time.time() - start

operator_column = data_exel['oper']

operator_column.value_counts()

print('Enlapsed time: ', elapsed_time)

data_exel.head()

Enlapsed time:  93.07183003425598

,data,ora,st,oper,operazione,nota,prodotto,codice,ditta prod.,imp/sc,pezzi,giac,var. bd,var. mag.
0,2020-04-01,08:25:00,1.0,NaN,VAR. PREZZO BD,NaN,PRANAROM CIRCULAR BIOGELGAMB,979817778.0,HERBALGEM ITALIA S,16.35,NaN,NaN,-0.15,NaN
1,2020-04-01,08:25:00,1.0,NaN,VAR. PREZZO BD,NaN,PRANAROM AROMAPIC GELLEN40ML,979817754.0,HERBALGEM ITALIA S,10.95,NaN,NaN,10.95,NaN
2,2020-04-01,08:25:00,1.0,NaN,VAR. PREZZO BD,NaN,OLIO SMAGLIATURE 100ML,978868053.0,WELEDA ITALIA SRL,21.4,NaN,1,0.40,0.4
3,2020-04-01,08:25:00,1.0,NaN,VAR. PREZZO BD,NaN,BABY CREMA PROTETTIVACAL75ML,978867974.0,WELEDA ITALIA SRL,10.7,NaN,2,0.20,0.4
4,2020-04-01,08:25:00,1.0,NaN,VAR. PREZZO BD,NaN,DECOTTO DI BETULLA 250ML,976785865.0,WELEDA ITALIA SRL,17.3,NaN,NaN,0.30,NaN

In [33]:
#Abbozzo di algoritmo per le Sinonimie

#1) Remove NaN values
ab = data_exel[['prodotto','codice']].dropna(subset=['prodotto','codice'])
a  = data_exel['prodotto'].dropna()
b  = data_exel['codice'].dropna()

#2) Apply distincts
distinct_ab = ab.drop_duplicates(subset=['prodotto','codice'])
distinct_a  = a.drop_duplicates()
distinct_b  = b.drop_duplicates()

#3) Show results
print(distinct_ab.info())
print(distinct_a.info())
print(distinct_b.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18355 entries, 0 to 863040
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   prodotto  18355 non-null  object
 1   codice    18355 non-null  float64
dtypes: float64(1), object(1)
memory usage: 430.2+ KB
None
<class 'pandas.core.series.Series'>
Int64Index: 18843 entries, 0 to 908975
Series name: prodotto
Non-Null Count  Dtype
--------------  -----
18843 non-null  object
dtypes: object(1)
memory usage: 294.4+ KB
None
<class 'pandas.core.series.Series'>
Int64Index: 18365 entries, 0 to 863040
Series name: codice
Non-Null Count  Dtype
--------------  -----
18365 non-null  float64
dtypes: float64(1)
memory usage: 287.0 KB
None
0         979817778.0
1         979817754.0
2         978868053.0
3         978867974.0
4         976785865.0
             ...
862641     48444107.0
862710    982881714.0
862781    980478604.0
862900    934423904.0
863040    982396107.0
Name: codice, Length: 18365, dtype: float64

In [45]:
import numpy as np
b_array = np.array(distinct_b)
ab_array = np.array(distinct_ab['codice'])

main_list = np.setdiff1d(b_array,ab_array)
main_list

array([1.05382400e+06, 6.00473793e+08, 6.00473805e+08, 6.66667124e+08,
       6.66667706e+08, 6.66667795e+08, 6.66668114e+08, 6.66668417e+08,
       8.08848182e+08, 9.83321151e+08])

In [84]:
def isOneToOne(df, col1, col2):
    first = df.drop_duplicates([col1, col2]).groupby(col1)[col2].count().max()
    second = df.drop_duplicates([col1, col2]).groupby(col2)[col1].count().max()
    return second


isOneToOne(distinct_ab, 'prodotto', 'codice')

9

In [104]:
def get_relation(df, col1, col2):        
    first_max = df[[col1, col2]].groupby(col1).count().max()[0]
    second_max = df[[col1, col2]].groupby(col2).count().max()[0]

    if first_max==1:
        if second_max==1:
            return 'one-to-one'
        else:
            return 'one-to-many'
    else:
        if second_max==1:
            return 'many-to-one'
        else:
            return 'many-to-many'

get_relation(data_exel, 'prodotto', 'codice')

'many-to-many'

In [12]:
import csv

a = set()
b = set()
ab = set()
file = csv.reader(open('./Fact_Tables/pharma.csv'), delimiter=";")
for row in file:
    if (row[0] != "") and (row[8] != ""):
        a.add(row[0])
        b.add(row[8])
        ab.add(row[0]+" - "+row[8])

print("a:", len(a))
print("b:", len(b))
print("ab:", len(ab))

a: 571
b: 1183
ab: 113663

In [115]:

start = time.time()

data_csv = pd.read_csv('./Fact_Tables/pharma.csv', encoding = "Windows-1252", sep = ';', low_memory=False)
#URL = 'https://drive.google.com/file/d/1Q997Mig3nQZXkWl2IPrjibi_nDtJ-tz4/view?usp=share_link'
#path = 'https://drive.google.com/uc?export=download&id='+URL.split('/')[-2]

#data_csv = pd.read_csv(path, encoding = "Windows-1252", sep = ';', low_memory=False)

elapsed_time = time.time() - start

operator_column = data_csv['oper']

operator_column.value_counts()

print('Enlapsed time: ', elapsed_time)

data_csv.head()

Enlapsed time:  1.3997383117675781

,data,ora,st,oper,operazione,nota,prodotto,codice,ditta prod.,imp/sc,pezzi,giac,var. bd,var. mag.
0,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,PRANAROM CIRCULAR BIOGELGAMB,979817778.0,HERBALGEM ITALIA S,"16,35 €",NaN,NaN,"-0,15",NaN
1,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,PRANAROM AROMAPIC GELLEN40ML,979817754.0,HERBALGEM ITALIA S,"10,95 €",NaN,NaN,"10,95",NaN
2,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,OLIO SMAGLIATURE 100ML,978868053.0,WELEDA ITALIA SRL,"21,40 €",NaN,1,"0,4","0,4"
3,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,BABY CREMA PROTETTIVACAL75ML,978867974.0,WELEDA ITALIA SRL,"10,70 €",NaN,2,"0,2","0,4"
4,01/04/2020,08:25,1.0,NaN,VAR. PREZZO BD,NaN,DECOTTO DI BETULLA 250ML,976785865.0,WELEDA ITALIA SRL,"17,30 €",NaN,NaN,"0,3",NaN

In [31]:
%run CleverSchemaDetectionCSV.ipynb

#if the inferred data type is INTEGER and there is a presence of FLOAT on the results , then the result will be FLOAT
conditions = {"INTEGER":"FLOAT"}

csv_infer = csv_schema_inference.CsvSchemaInference(portion=0.9, max_length=100, batch_size = 200000, acc = 0.8, seed=2, header=True, sep=";", conditions = conditions)
pathfile = './Fact_Tables/CUBE_AND_HIERARCHIES.txt'

aprox_schema = csv_infer.run_inference(pathfile)

csv_infer.pretty(aprox_schema)

0
	name
		ID
	type
		INTEGER
	nullable
		False
1
	name
		ITEM
	type
		STRING
	nullable
		False
2
	name
		SEGMENT
	type
		STRING
	nullable
		True
3
	name
		CATEGORY
	type
		STRING
	nullable
		False
4
	name
		BRAND
	type
		STRING
	nullable
		False
5
	name
		PROD_TYPE
	type
		STRING
	nullable
		False
6
	name
		PROD_TARGET
	type
		STRING
	nullable
		False
7
	name
		PORTFOLIO
	type
		STRING
	nullable
		True
8
	name
		----------
	type
		STRING
	nullable
		False
9
	name
		ID
	type
		INTEGER
	nullable
		False
10
	name
		CUSTOMER_NAME
	type
		STRING
	nullable
		False
11
	name
		AGENT
	type
		STRING
	nullable
		False
12
	name
		ORGANIZATION
	type
		STRING
	nullable
		False
13
	name
		ORGANIZATION_ID
	type
		INTEGER
	nullable
		False
14
	name
		CUST_CLASS
	type
		STRING
	nullable
		True
15
	name
		CUST_CATEGORY
	type
		STRING
	nullable
		False
16
	name
		----------
	type
		STRING
	nullable
		False
17
	name
		KPI
	type
		STRING
	nullable
		False
18
	name
		----------
	type
		STRING
	nullable
		False
19
	name
		Year
	type
		INTEGER
	nullable
		False
20
	name
		----------
	type
		STRING
	nullable
		False
21
	name
		YTD_PTD
	type
		STRING
	nullable
		False
22
	name
		----------
	type
		STRING
	nullable
		False
23
	name
		January
	type
		STRING
	nullable
		True
24
	name
		February
	type
		STRING
	nullable
		True
25
	name
		March
	type
		STRING
	nullable
		False
26
	name
		April
	type
		STRING
	nullable
		False
27
	name
		May
	type
		STRING
	nullable
		False
28
	name
		June
	type
		STRING
	nullable
		False
29
	name
		July
	type
		STRING
	nullable
		False
30
	name
		August
	type
		STRING
	nullable
		False
31
	name
		September
	type
		STRING
	nullable
		False
32
	name
		October
	type
		STRING
	nullable
		False
33
	name
		November
	type
		STRING
	nullable
		False
34
	name
		December
	type
		STRING
	nullable
		False
35
	name

	type
		STRING
	nullable
		True

In [11]:
from quantulum3 import parser
quants = parser.parse('1.9 $')
quants

[Quantity(1.9, "Unit(name="dollar", entity=Entity("currency"), uri=Dollar)")]

In [42]:
from geotext import GeoText
places = GeoText('BR')
places.cities

In [13]:
import geograpy
places = geograpy.get_geoPlace_context(text='Piedmont')
print(places)

# CAP
# coordinate
# Indirizzi

countries=['United States of America', 'Canada', 'Australia', 'Russia', 'France']
regions=[]
cities=['Piedmont']
other=[]

In [ ]:
# Test per looppare sulla diagonale superiore della matrice

labels = df_correlazioni.columns

for row in range(0, len(df_correlazioni)-1):
    for col in range(row+1, len(df_correlazioni)):
        rel = df_correlazioni.loc[labels[row],labels[col]]
        if rel == 'many to one':
            print(labels[row],labels[col])
            print(rel)

In [1]:
# Algoritmo 1

'''''
df_relazioni = df_fact_table[tabelle_esterne.keys()]
init_columns = np.array(df_relazioni.columns)
init_length = len(init_columns)

relazioni = {}

for column in range(0,len(init_columns)-1):
    
    b = []
    
    for dim in range(1,len(init_columns)):
        
        b.append(get_relation(df_relazioni, init_columns[0], init_columns[dim]))
        
    a = np.empty((init_length-len(init_columns),))
    a[:] = np.nan
    b = np.array(b)
    relazioni[init_columns[0]] = np.concatenate((a, b), axis=None)
        
    init_columns = np.delete(init_columns, 0)
    
    
df_correlazioni = pd.DataFrame(relazioni)
df_correlazioni = df_correlazioni.set_index(df_relazioni.columns[1:])
df_correlazioni
'''''

"''\ndf_relazioni = df_fact_table[tabelle_esterne.keys()]\ninit_columns = np.array(df_relazioni.columns)\ninit_length = len(init_columns)\n\nrelazioni = {}\n\nfor column in range(0,len(init_columns)-1):\n    \n    b = []\n    \n    for dim in range(1,len(init_columns)):\n        \n        b.append(get_relation(df_relazioni, init_columns[0], init_columns[dim]))\n        \n    a = np.empty((init_length-len(init_columns),))\n    a[:] = np.nan\n    b = np.array(b)\n    relazioni[init_columns[0]] = np.concatenate((a, b), axis=None)\n        \n    init_columns = np.delete(init_columns, 0)\n    \n    \ndf_correlazioni = pd.DataFrame(relazioni)\ndf_correlazioni = df_correlazioni.set_index(df_relazioni.columns[1:])\ndf_correlazioni\n"